CREATE TABLE LOGS
(
  ID_LOG INTEGER DEFAULT SEQ_LOG.NEXTVAL PRIMARY KEY NOT NULL
, TABLE_NAME VARCHAR2(20) NOT NULL
, OPERATION VARCHAR2(60)
, OLD_VALUE VARCHAR2(300)
, NEW_VALUE VARCHAR2(300)
, EVENT_DATE TIMESTAMP default sysdate 
, INSERT_DATE TIMESTAMP default sysdate 
);